### PR TITLE
SPI busy flag may cause deadlock

### PR DESCRIPTION
**Pull request by mingpepe**
If user call `completeTransmit` in `onTransmit` event, the `busy` flag will be set `false` then `true`. Which may cause emulator waiting for it.

### CODE REVIEW

**Comment by urish** [comment]
Thanks again! 

I'm curious, what PIO project are you working on?

**Comment by mingpepe** [comment]
To implement camera interface. Not only PIO but trying to run my pico code on this emulator, but seems still have some issues to solve.

**Comment by urish** [comment]
Which issues, for instance?

**Comment by mingpepe** [comment]
I will create new issue later.

**Pull request merged**
